test:
  git:
    name: testGitRegistration12
account:
  ui:
    frictionlessBrands: deepakTest12
gips-client-properties:
  ctaWelcome: test12
  baseUrl: https://test.com/

spring:
  security:
    oauth2:
      client:
        registration:
          gips:
            client-id: 1234